name: deploy pr website
on: [pull_request]

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  deploy:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'yarn'
      - name: build
        run: ./scripts/build_testnet.sh
      - uses: amondnet/vercel-action@v25.2.0 #deploy
        id: vercel_deploy
        with:
          scope: ${{ secrets.TEAM_ID_1 }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN_1 }} # Required
          # vercel-args: '--prebuilt'
          vercel-org-id: ${{ secrets.ORG_ID_1}} #Required
          vercel-project-id: ${{ secrets.PROJECT_ID_1}} #Required
