name: Playwright test for web
on:
  workflow_dispatch:
    inputs:
      test_url:
        description: 'Test Url'
        required: true
        type: string
      filter:
        description: 'Test Filter'
        required: false
        type: string

jobs:
  test:
    timeout-minutes: 90
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: install
        run: ./scripts/install_testnet.sh
      - name: run playwright test
        env:
          VITE_PLAYWRIGHT_TEST_URL: ${{ inputs.test_url }}
        run: |
          cd apps/web
          npx playwright install --with-deps chromium
          npx playwright test ${{ inputs.filter }}
      - name: upload test result artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: web-test-report-${{ github.run_number }}-${{ github.run_attempt }}
          path: ./apps/web/playwright-report/index.html
